### ISSUE TITLE
Update to 10.14.5

### ISSUE THREAD

**Issue by dfa1234** [BradenM/Hackintosh-7700k-R9_390-iGPU#3]
I need last xcode so I will try to update to 10.14.5
Do you think that this configuration will work?
I give it a try right now.

**Comment by dfa1234** [comment]
The update went fine (clean install)
I had to add my kext (AtherosE2200Ethernet.kext) like the last time 
Thank again for this magnifient project :)

**Comment by BradenM** [comment]
Awesome!

Glad I could help, I no longer use this hackintosh as my main work station but I'll take a look at updating the kexts here soon.
